plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id "io.freefair.lombok" version "9.5.0"
}

group 'tech.aomi.common'
version '1.0.14_0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://nexus.stelarx.tech/repository/maven-snapshots/"
    }
}

test {
    useJUnitPlatform()
}

dependencies {
    compileOnly "org.slf4j:slf4j-api:1.7.25"

    compileOnly "com.squareup.okhttp3:okhttp:4.12.0"

    compileOnly "commons-codec:commons-codec:1.16.1"
    compileOnly "org.apache.commons:commons-lang3:3.14.0"

    compileOnly "com.dyuproject.protostuff:protostuff-core:1.0.12"
    compileOnly "com.dyuproject.protostuff:protostuff-runtime:1.0.12"

    compileOnly "org.objenesis:objenesis:2.5.1"

    compileOnly "com.fasterxml.jackson.core:jackson-core:2.17.0"
    compileOnly "com.fasterxml.jackson.core:jackson-databind:2.17.0"
    compileOnly "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0"
    compileOnly "com.fasterxml.jackson.core:jackson-core:2.17.0"
    compileOnly "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.0"


    compileOnly "org.apache.poi:poi:5.2.5"
    compileOnly "org.apache.poi:poi-ooxml:5.2.5"

    testImplementation('org.junit.jupiter:junit-jupiter:5.7.0')
    testImplementation "com.fasterxml.jackson.core:jackson-core:2.17.0"
    testImplementation "com.fasterxml.jackson.core:jackson-databind:2.17.0"
    testImplementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0"
    testImplementation "com.fasterxml.jackson.core:jackson-core:2.17.0"
    testImplementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.0"

}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        maven {
            url = project.version.endsWith('-SNAPSHOT')
                    ? 'https://nexus.stelarx.tech/repository/maven-snapshots/'
                    : 'https://nexus.stelarx.tech/repository/maven-releases/'
            credentials {
                username System.getenv('REPO_USERNAME')
                password System.getenv('REPO_PASSWORD')
            }
        }
    }
}
